{
 "title": "Fugu Mppt",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "P",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"P\") as P, mean(\"P_prev\") as P_prev, mean(\"P_raw\") as P_raw, mean(\"P_filt\") as P_filt FROM \"mppt\" WHERE $timeFilter GROUP BY time($__interval), device fill(null)",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "P_prev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "P_raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "esp32_proto_mppt" }
     ]
    }
   ]
  },
  {
   "title": "U_in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "select": [
      [
       { "params": [ "U" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "U" ], "type": "alias" }
      ],
      [
       { "params": [ "U_in_raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "U_raw" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "U_out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "select": [
      [
       { "params": [ "U_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "U_out" ], "type": "alias" }
      ],
      [
       { "params": [ "U_out_raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "U_out_raw" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "I",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "I" ], "type": "alias" }
      ],
      [
       { "params": [ "I_raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "I_raw" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"E\") as E , mean(\"E_today\") as E_today FROM \"mppt\" WHERE $timeFilter GROUP BY time($__interval), device fill(null)",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "P_prev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "P_raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "esp32_proto_mppt" }
     ]
    }
   ]
  },
  {
   "title": "PWM duty cycle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"I\") as I, mean(\"U\") as U, mean(\"P\") as P FROM \"mppt\" WHERE (\"device\" = 'esp32_proto_mppt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pwm_duty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "dP",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"I\") as I, mean(\"U\") as U, mean(\"P\") as P FROM \"mppt\" WHERE (\"device\" = 'esp32_proto_mppt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "dP" ], "type": "alias" }
      ],
      [
       { "params": [ "dP_thres" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "dP_thres" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pwm direction",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"I\") as I, mean(\"U\") as U, mean(\"P\") as P FROM \"mppt\" WHERE (\"device\" = 'esp32_proto_mppt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pwm_dir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "pwm_dir_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power and Duty Cycle",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"P\") as P, mean(\"P_prev\") as P_prev, mean(\"P_raw\") as P_raw , mean(\"P_filt\") as P_filt FROM \"mppt\" WHERE $timeFilter GROUP BY time($__interval), device fill(null)",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "P_prev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "P_raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "esp32_proto_mppt" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mcu" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "select": [
      [
       { "params": [ "pwm_duty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "duty" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "P/dutyCycle scatter",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "v1" ], "type": "alias" }
      ],
      [
       { "params": [ "pwm_duty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "v2" ], "type": "alias" }
      ],
      [
       { "params": [ "U_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "v3" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "v1" ], "type": "alias" }
      ],
      [
       { "params": [ "pwm_duty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "v2" ], "type": "alias" }
      ],
      [
       { "params": [ "U_in_raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "v3" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "P_filt/dutyCycle scatter",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 10, "w": 22, "x": 1, "y": 78 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "select": [
      [
       { "params": [ "P_filt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "v1" ], "type": "alias" }
      ],
      [
       { "params": [ "pwm_duty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "v2" ], "type": "alias" }
      ],
      [
       { "params": [ "U_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "v3" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"I\") as I, mean(\"U\") as U, mean(\"P\") as P FROM \"mppt\" WHERE (\"device\" = 'esp32_proto_mppt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mppt_state" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cv_lim_idx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"I\") as I, mean(\"U\") as U, mean(\"P\") as P FROM \"mppt\" WHERE (\"device\" = 'esp32_proto_mppt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cv_lim_idx" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "speed scale",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"I\") as I, mean(\"U\") as U, mean(\"P\") as P FROM \"mppt\" WHERE (\"device\" = 'esp32_proto_mppt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "speed_scale" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LS PWM duty cycle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"I\") as I, mean(\"U\") as U, mean(\"P\") as P FROM \"mppt\" WHERE (\"device\" = 'esp32_proto_mppt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pwm_ls_duty" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "pwm_ls_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "pwm_ls_max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mppt",
     "query": "SELECT mean(\"I\") as I, mean(\"U\") as U, mean(\"P\") as P FROM \"mppt\" WHERE (\"device\" = 'esp32_proto_mppt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mcu_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mcu" ], "type": "alias" }
      ],
      [
       { "params": [ "ntc_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ntc" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}