{
 "title": "smart-shunt",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "mean current (mA)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "smart_shunt",
     "query": "SELECT mean(\"I\")*1000 FROM \"smart_shunt\" WHERE $timeFilter GROUP BY time($__interval), \"device\"  fill(null)",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "smart_shunt",
     "select": [
      [
       { "params": [ "U" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "pwer",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "smart_shunt",
     "query": "SELECT mean(\"P\")*-1000 FROM \"smart_shunt\" WHERE $timeFilter GROUP BY time($__interval), \"device\" fill(previous)",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "smart_shunt",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * -1000 * 1.00234" ], "type": "math" },
       { "params": [ "esp32_ads_corr" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32_ADS" }
     ]
    }
   ]
  },
  {
   "title": "smooth pwr",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "smart_shunt",
     "query": "SELECT mean(\"P\")*-1000 FROM \"smart_shunt\" WHERE $timeFilter GROUP BY time($__interval), \"device\" fill(previous)",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         40
        ],
        "type": "moving_average"
       },
       { "params": [ "* -1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Power (mW)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_shunt",
     "query": "SELECT mean(\"P\") *1000 AS \"P_in\" FROM \"smart_shunt\" WHERE (\"device\" = 'ESP32_ADS') AND $timeFilter",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Curren (mA)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_shunt",
     "query": "SELECT mean(\"P\") *1000 AS \"P_in\" FROM \"smart_shunt\" WHERE (\"device\" = 'ESP32_ADS') AND $timeFilter",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "smart_shunt",
     "select": [
      [
       { "params": [ "E" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "max/min current (mA)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "smart_shunt",
     "query": "SELECT min(\"I_min\")*1000 as I_min, max(I_max)*1000 as I_max FROM \"smart_shunt\" WHERE $timeFilter GROUP BY time($__interval), \"device\"  fill(null)",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "dt max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_shunt",
     "select": [
      [
       { "params": [ "dt_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "timeouts" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "timeouts" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}